{{- $component_type := "backend" }}
{{- with (get .Values $component_type) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $component_type }}
  labels:
    {{- include "common_labels" (list $ $component_type) | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  strategy: 
    type: {{ .strategy }}
  selector:
    matchLabels:
      {{- include "common_labels" (list $ $component_type) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common_labels" (list $ $component_type) | nindent 8 }}
    spec:
      containers:
        - name: {{ $component_type }}
          image: {{ .image }}
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: /api/v1
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: OPENAI_API_KEY
            - name: FIREBASE_CREDENTIALS_PATH
              value: /secrets/firebase-credentials.json
          volumeMounts:
            - name: huggingface-hub-token
              mountPath: /root/.cache/huggingface/token
              subPath: token
            - name: firebase-credentials
              mountPath: /secrets
          ports:
            - containerPort: {{ .port }}
      volumes:
        - name: huggingface-hub-token
          secret:
            secretName: huggingface-hub
            items:
              - key: HUGGING_FACE_HUB_TOKEN
                path: token
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
        - name: openai
          secret:
            secretName: openai
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $component_type }}
  labels:
    {{- include "common_labels" (list $ $component_type) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "common_labels" (list $ $component_type) | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      name: http
---
{{- end -}}
